version: '3.8'

services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - zookeeper
      - kafka
    
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  customer-service:
    container_name: customer-service
    build: ./customer_service
    environment:
      - ENVIRONMENT=develop
      - POSTGRES_HOST=database-1.c9lxq3r1itbt.us-east-1.rds.amazonaws.com
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=customerdb_abdulloh
      - POSTGRES_USER=abdulloh
      - POSTGRES_PASSWORD=abdulloh
      - POST_SERVICE_HOST=post-service
      - POST_SERVICE_PORT=8000
      - REVIEW_SERVICE_HOST=review-service
      - REVIEW_SERVICE_PORT=1111
    ports:
      - "8002:8002"
    links:
      - "post-service"
      - "review-service"    
      - "kafka"

  post-service:
    container_name: post-service
    build: ./post-service
    environment:
      - ENVIRONMENT=develop
      - POSTGRES_HOST=database-1.c9lxq3r1itbt.us-east-1.rds.amazonaws.com
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postdb_abdulloh
      - POSTGRES_USER=abdulloh
      - POSTGRES_PASSWORD=abdulloh
      - REVIEW_SERVICE_HOST=review-service
      - REVIEW_SERVICE_PORT=1111
      - CUSTOMER_SERVICE_HOST=customer-service
      - CUSTOMER_SERVICE_PORT=8002
    ports:
      - "8000:8000"
    links:
      - "review-service"
      - "kafka"

  review-service:
    container_name: review-service
    build: ./reyting_service
    environment:
      - ENVIRONMENT=develop
      - POSTGRES_HOST=database-1.c9lxq3r1itbt.us-east-1.rds.amazonaws.com
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=reytingdb_abdulloh
      - POSTGRES_USER=abdulloh
      - POSTGRES_PASSWORD=abdulloh
    ports:
      - "1111:1111"
  api:
    container_name: api
    build: ./api-exam
    environment:
      - ENVIRONMENT=develop
      - CUSTOMER_SERVICE_HOST=customer-service
      - CUSTOMER_SERVICE_PORT=8002
      - POST_SERVICE_HOST=post-service
      - POST_SERVICE_PORT=8000
      - REVIEW_SERVICE_HOST=review-service
      - REVIEW_SERVICE_PORT=1111
      - AUTH_PATHDB=./config/auth.conf
    links:
      - "customer-service"
      - "post-service"
      - "review-service"
    ports:
      - "8081:8081"
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6371:6379"

  